# masukkan suhu dalam celcius:25
# suhu dalam fahrenheith: 77.0
def celsius_to_fahrenheith(celsius): 
    #Conversion and Output 
     fahrenheith = (celsius * 9/5) + 32
     fahrenheith 

#input
celsius_input = float (input("masukkan sushu dalam celsius:"))

#conversion and output 
fahrenheith_output = celsius_to_fahrenheith (celsius_input)
print (f"suhu dalam fahrenheith: {fahrenheith_output}")